org: sandeepkhoj
app: cognito-trigger
service: cognito-trigger

frameworkVersion: '3'

custom:
  STAGE: ${self:provider.stage}
  CONFIG: ${file(./config/config.js):CONFIG}

provider:
  name: aws
  region: us-east-2
  iam:
    role: arn:aws:iam::829901743612:role/CognitoTiggerRole
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true
  environment:
    STAGE: ${self:provider.stage}
    DATABASE_URL: ${self:custom.CONFIG.DATABASE_URL}
    IAHV_CLIENT_ID: ${self:custom.CONFIG.IAHV_CLIENT_ID}
    HB_CLIENT_ID: ${self:custom.CONFIG.HB_CLIENT_ID}
    AOL_CLIENT_ID: ${self:custom.CONFIG.AOL_CLIENT_ID}
    CDK_STACK_NAME: passwordless-example
    CDK_STACK_SES_FROM_ADDRESS: app.support@us.artofliving.org

functions:
  customMessage:
    handler: src/functions/customMessage.handler
    name: ${sls:stage}-customMessage
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: CustomMessage
          existing: true

  UserMigration:
    handler: src/functions/migrateUser.handler
    name: ${sls:stage}-migrateUser
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: UserMigration
          existing: true

  preAuthentication:
    handler: src/functions/preAuthentication.handler
    name: ${sls:stage}-preAuthentication
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: PreAuthentication
          existing: true

  postAuthentication:
    handler: src/functions/postAuthentication.handler
    name: ${sls:stage}-postAuthentication
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: PostAuthentication
          existing: true

  postConfirmation:
    handler: src/functions/postConfirmation.handler
    name: ${sls:stage}-postConfirmation
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: PostConfirmation
          existing: true

  preSignup:
    handler: src/functions/preSignup.handler
    name: ${sls:stage}-preSignup
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: PreSignUp
          existing: true

  defineAuthChallenge:
    handler: src/functions/defineAuthChallenge.handler
    name: ${sls:stage}-defineAuthChallenge
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: DefineAuthChallenge
          existing: true
    environment:
      LOG_LEVEL: DEBUG
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

  createAuthChallenge:
    handler: src/functions/createAuthChallenge.handler
    name: ${sls:stage}-createAuthChallenge
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: CreateAuthChallenge
          existing: true
    environment:
      FIDO2_ENABLED: TRUE
      DYNAMODB_AUTHENTICATORS_TABLE: cognito-passwordless-Fido2AuthenticatorsTablePasswordlessBDEAEEE6-X5X3PVGEKZR7
      DYNAMODB_SECRETS_TABLE: cognito-passwordless-SecretsTablePasswordless8B664A61-1K60WW37ERANU
      EXPOSE_USER_CREDENTIAL_IDS: TRUE
      KMS_KEY_ID: alias/Passwordless-cognito-passwordless
      LOG_LEVEL: DEBUG
      MAGIC_LINK_ENABLED: TRUE
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      ALLOWED_APPLICATION_ORIGINS:
      ALLOWED_ORIGINS: http://localhost:3000,https://dc2t9waxh7vse.cloudfront.net

  verifyAuthChallenge:
    handler: src/functions/verifyAuthChallenge.handler
    name: ${sls:stage}-verifyAuthChallenge
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: VerifyAuthChallengeResponse
          existing: true
    environment:
      FIDO2_ENABLED: TRUE
      DYNAMODB_AUTHENTICATORS_TABLE: cognito-passwordless-Fido2AuthenticatorsTablePasswordlessBDEAEEE6-X5X3PVGEKZR7
      DYNAMODB_SECRETS_TABLE: cognito-passwordless-SecretsTablePasswordless8B664A61-1K60WW37ERANU
      EXPOSE_USER_CREDENTIAL_IDS: TRUE
      KMS_KEY_ID: alias/Passwordless-cognito-passwordless
      LOG_LEVEL: DEBUG
      MAGIC_LINK_ENABLED: TRUE
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      ALLOWED_APPLICATION_ORIGINS:
      ALLOWED_ORIGINS: http://localhost:3000,https://dc2t9waxh7vse.cloudfront.net
      ALLOWED_RELYING_PARTY_IDS: localhost,dc2t9waxh7vse.cloudfront.net

  preToken:
    handler: src/functions/preToken.handler
    name: ${sls:stage}-preToken
    events:
      - cognitoUserPool:
          pool: aol-${sls:stage}
          trigger: PreTokenGeneration
          existing: true
    environment:
      CLIENT_METADATA_PERSISTED_KEYS: signInMethod,consent_id
      LOG_LEVEL: DEBUG
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
