name: 🚀 Deploy serverless prod app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🏗 Setup yarn
        run: npm install -g yarn

      - name: 📦 Install packages
        run: yarn install

      - name: 🚀 Serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{secrets.PROD_DATABASE_URL}}
          IAHV_CLIENT_ID: ${{secrets.PROD_IAHV_CLIENT_ID}}
          HB_CLIENT_ID: ${{secrets.PROD_HB_CLIENT_ID}}
          AOL_CLIENT_ID: ${{secrets.PROD_AOL_CLIENT_ID}}
          COGNITO_USER_POOL_ID: ${{secrets.PROD_COGNITO_USER_POOL_ID}}
          REGION: ${{secrets.REGION}}
          ACCOUNT_ID: ${{secrets.ACCOUNT_ID}}
          CORS_ALLOWED_ORIGINS: ${{secrets.PROD_CORS_ALLOWED_ORIGINS}}
          ALLOWED_ORIGINS: ${{secrets.PROD_CORS_ALLOWED_ORIGINS}}
          ALLOWED_RELYING_PARTY_IDS: ${{secrets.PROD_ALLOWED_RELYING_PARTY_IDS}}
